### ISSUE TITLE
Exclude directory

### ISSUE THREAD

**Issue by avucic** [iberianpig/ranger-explorer.vim#2]
How I can exclude directory from listing? 
For ex. node_modules? Thanks

**Comment by iberianpig** [comment]
Please try to ignore them with the setting below
https://github.com/ranger/ranger/wiki/VCS-integration

**Comment by iberianpig** [comment]
Oh, Sorry, it cannot ignore list.
it is only give displaying the mark for VCS on ranger.

**Comment by iberianpig** [comment]
I think the feautre should be implemented on ranger rather than this plugin.
